import { 
  FaInstagram, FaYoutube, FaTwitter, FaFacebook, FaLinkedin, FaSnapchatGhost, FaPinterest, FaTiktok, FaReddit, FaGithub, FaDribbble, FaBehance, FaMedium, FaSpotify, FaSoundcloud, FaTwitch, FaDiscord, FaWhatsapp, FaTelegram, FaGlobe
} from 'react-icons/fa';
import { SiThreads, SiOnlyfans, SiSubstack, SiBuymeacoffee, SiPatreon, SiEtsy, SiAmazon, SiShopify, SiGumroad, SiVizitlink } from 'react-icons/si';
import { MdEmail } from 'react-icons/md';

export const socialIconsMap = {
  instagram: FaInstagram,
  youtube: FaYoutube,
  twitter: FaTwitter,
  facebook: FaFacebook,
  linkedin: FaLinkedin,
  threads: SiThreads,
  tiktok: FaTiktok,
  whatsapp: FaWhatsapp,
  snapchat: FaSnapchatGhost,
  pinterest: FaPinterest,
  reddit: FaReddit,
  github: FaGithub,
  dribbble: FaDribbble,
  behance: FaBehance,
  medium: FaMedium,
  spotify: FaSpotify,
  soundcloud: FaSoundcloud,
  twitch: FaTwitch,
  discord: FaDiscord,
  telegram: FaTelegram,
  email: MdEmail,
  onlyfans: SiOnlyfans,
  substack: SiSubstack,
  buymeacoffee: SiBuymeacoffee,
  patreon: SiPatreon,
  etsy: SiEtsy,
  amazon: SiAmazon,
  shopify: SiShopify,
  gumroad: SiGumroad,
  vizitlink: SiVizitlink,
  website: FaGlobe,
  default: FaGlobe,
};

export const socialColorsMap = {
  instagram: '#E4405F',
  youtube: '#FF0000',
  twitter: '#1DA1F2',
  facebook: '#1877F2',
  linkedin: '#0A66C2',
  threads: '#000000',
  tiktok: '#000000',
  whatsapp: '#25D366',
  snapchat: '#FFFC00',
  pinterest: '#E60023',
  reddit: '#FF4500',
  github: '#181717',
  dribbble: '#EA4C89',
  behance: '#0057FF',
  medium: '#000000',
  spotify: '#1DB954',
  soundcloud: '#FF8800',
  twitch: '#9146FF',
  discord: '#5865F2',
  telegram: '#2CA5E0',
  email: '#EA4335',
  onlyfans: '#00B0FF',
  substack: '#FF6719',
  buymeacoffee: '#FFDD00',
  patreon: '#FF424D',
  etsy: '#F16521',
  amazon: '#FF9900',
  shopify: '#7AB55C',
  gumroad: '#FF9000',
  vizitlink: '#00DA00',
  website: '#4A5568',
  default: '#4A5568',
};
